// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKdk9MGhyrSMETlQNHmTbBhG5ioW_v7I',
    appId: '1:485550786842:web:4653e124edabfcdf2344a3',
    messagingSenderId: '485550786842',
    projectId: 'flutter-internship-project',
    authDomain: 'flutter-internship-project.firebaseapp.com',
    storageBucket: 'flutter-internship-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcv1kqygX3CifbcHWPyI-dqPYbbE2nqoQ',
    appId: '1:485550786842:android:0937bcd70fadb1f32344a3',
    messagingSenderId: '485550786842',
    projectId: 'flutter-internship-project',
    storageBucket: 'flutter-internship-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JExgjpccVYYC83qLa3JNKSc_tGxAFFM',
    appId: '1:485550786842:ios:2852e87cea7c77282344a3',
    messagingSenderId: '485550786842',
    projectId: 'flutter-internship-project',
    storageBucket: 'flutter-internship-project.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JExgjpccVYYC83qLa3JNKSc_tGxAFFM',
    appId: '1:485550786842:ios:fec0d113b7160b542344a3',
    messagingSenderId: '485550786842',
    projectId: 'flutter-internship-project',
    storageBucket: 'flutter-internship-project.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
